### ISSUE TITLE
"Show Detail View" causes deleted variants to have blank page

### ISSUE THREAD

**Issue by e-t-k** [BRCAChallenge/brca-exchange#1468]
Putting BRCAExchange into "Detail View" mode causes the variants page to be blank for many deleted variants.

It's unclear to me how important this is. It seems likely that deleted variants are never a "current variant" which would mean that fixing their pages is not important. (I am not certain that it only happens on deleted variants but I could not find a non-deleted variant that had the problem.)

Deleted variant = page which mentions "Note: This variant has been removed from the BRCA Exchange"

Browser: both Chrome and Firefox on macOS Big Sur

**To reproduce:**
- Navigate to https://brcaexchange.org/variant/25727
- Click "Show Detail View for this Variant"
- In the popup, click "YES".  Nothing noticeable happens.
- Refresh the page
- Page is now blank except for header and footer:
----
![image](https://github.com/BRCAChallenge/brca-exchange/assets/19291809/d77139a3-f89a-4d8f-853e-c28e5f3457e7)
---
**Workaround:**
- Navigate to a non-deleted variant eg https://brcaexchange.org/variant/840836 
- Click "Show Summary View of This Variant" at the bottom
- Refresh the [original 25727 page](https://brcaexchange.org/variant/25727) and observe that it is back to summary view.

When the page is blank, this error appears in the web console:
```
caught TypeError: Cannot read properties of null (reading 'varType')
    at main.js:92347:79
    at arrayMap (main.js:93223:24)
    at Object.map (main.js:102164:15)
    at ComputationalPredictionTile.render (main.js:92341:31)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (main.js:11409:35)
    at ReactCompositeComponentWrapper._renderValidatedComponent (main.js:11429:33)
    at ReactCompositeComponentWrapper.wrapper [as _renderValidatedComponent] (main.js:5160:22)
    at ReactCompositeComponentWrapper.mountComponent (main.js:11042:31)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (main.js:5160:22)
    at Object.mountComponent (main.js:9352:36)
```
which corresponds to [ComputationalPredictionTile.js#L118](https://github.com/BRCAChallenge/brca-exchange/blob/master/website/js/components/computationalprediction/ComputationalPredictionTile.js#L118)
suggesting that `variant.priors` is null.

- This reproduces on most of the deleted variants I spot checked ( [88795](https://brcaexchange.org/variant/88795?noRedirect=true), [81930](https://brcaexchange.org/variant/81930?noRedirect=true), [105382](https://brcaexchange.org/variant/105382?noRedirect=true)) but not all of them ( [280048](https://brcaexchange.org/variant/280048) ).

**Comment by melissacline** [comment]
Ellen, this is an excellent catch!  I suspect that this bug has been there
for a long time and just hasn't been observed (or reported) yet because it
involves an unusual situation (i.e. saving the hyperlink for a deleted
variant). The target functionality would be to show the (deleted) variant
data with a message indicating that the variant has been deleted.  A couple
thoughts:

   - This is yet another reason to get rid of the support for deleted
   variants, since it's buggy anyway!
   - In some ways, this situation arises from the URLs.  Something I'd like
   to do as a next step is move from URLs that describe the index of a variant
   in the database to persistent URLs, and a good candidate would be the
   ClinGen Allele Registry ID ( which is a "CA" followed by a string of
   digits, e.g. CA276312).  It's unique, perfectly web friendly, persistent,
   and meaningful (the ClinGen Allele Registry is a very comprehensive
   resource for all variants observed anywhere).  We have CA IDs defined for
   all BRCA Exchange variants.  Something to think about is: what would it
   take to make these our URLs?

Thanks!
Melissa
