### ISSUE TITLE
fallback for brca_pseudonym_generator failures

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#399]
If brca_pseudonym_generatory fails, the pipeline continues running and produces an incomplete output. It should catch the error and work accordingly (restart?).

Running brca_pseudonym_generator.py with the following args: ['python', 'brca_pseudonym_generator.py', '-i', '/Volumes/FLASH/UCSC/data/output/release/artifacts//aggregated.tsv', '-p', '-j', '/Volumes/FLASH/UCSC/brca-resources/hg18.fa', '-k', '/Volumes/FLASH/UCSC/brca-resources/hg19.fa', '-l', '/Volumes/FLASH/UCSC/brca-resources/hg38.fa', '-r', '/Volumes/FLASH/UCSC/brca-resources/refseq_annotation.hg18.gp', '-s', '/Volumes/FLASH/UCSC/brca-resources/refseq_annotation.hg19.gp', '-t', '/Volumes/FLASH/UCSC/brca-resources/refseq_annotation.hg38.gp', '-o', '/Volumes/FLASH/UCSC/data/output/release/built.tsv', '--artifacts_dir', '/Volumes/FLASH/UCSC/data/output/release/artifacts/']
standard output of subprocess:
WARNING dbfile.open_index: Falling back to hash index: unable to import bsddb
WARNING dbfile.open_index: Falling back to hash index: unable to import bsddb
WARNING dbfile.open_index: Falling back to hash index: unable to import bsddb

standard error of subprocess:
Traceback (most recent call last):
  File "brca_pseudonym_generator.py", line 239, in <module>
    sys.exit(main(sys.argv))
  File "brca_pseudonym_generator.py", line 188, in main
    protein_coord = variantmapper.c_to_p(var_c1)
  File "/Users/zackfischmann/.virtualenvs/brca/lib/python2.7/site-packages/hgvs/variantmapper.py", line 398, in c_to_p
    return super(EasyVariantMapper,self).c_to_p(var_c)
  File "/Users/zackfischmann/.virtualenvs/brca/lib/python2.7/site-packages/hgvs/variantmapper.py", line 239, in c_to_p
    reference_data = RefTranscriptData.setup_transcript_data(self.hdp, var_c.ac, pro_ac)
  File "/Users/zackfischmann/.virtualenvs/brca/lib/python2.7/site-packages/hgvs/variantmapper.py", line 210, in setup_transcript_data
    tx_seq = hdp.get_tx_seq(tx_ac)
  File "/Users/zackfischmann/.virtualenvs/brca/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 301, in get_tx_seq
    cur = self._get_cursor()
  File "/Users/zackfischmann/.virtualenvs/brca/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 396, in _get_cursor
    cur.execute('set search_path = '+pg_schema)
  File "/Users/zackfischmann/.virtualenvs/brca/lib/python2.7/site-packages/psycopg2/extras.py", line 120, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.DatabaseError: SSL SYSCALL error: Network is down

**Comment by melissacline** [comment]
@zfisch has this been done?
