### ISSUE TITLE
variantSet metadata not parsing correctly using GA4GH client.

### ISSUE THREAD

**Issue by jasteen** [BRCAChallenge/brca-exchange#659]
Following the python notebook using the GA4Gh client, I am unable to get past line 5.  Metadata for variantSets appears to contain an incorrect info field, or the GA4GH API schema has been updated.

stack trace as follows.

`>>> variant_sets = [i for i in c.search_variant_sets(dataset_id="brca")]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jste0021/scripts/virtualenv_testing/testing_project/lib/python2.7/site-packages/ga4gh/client/client.py", line 89, in _run_search_request
    protocol_request, object_name, protocol_response_class)
  File "/home/jste0021/scripts/virtualenv_testing/testing_project/lib/python2.7/site-packages/ga4gh/client/client.py", line 939, in _run_search_page_request
    response.text, protocol_response_class)
  File "/home/jste0021/scripts/virtualenv_testing/testing_project/lib/python2.7/site-packages/ga4gh/client/client.py", line 37, in _deserialize_response
    return protocol.fromJson(json_response_string, protocol_response_class)
  File "/home/jste0021/scripts/virtualenv_testing/testing_project/lib/python2.7/site-packages/ga4gh/schemas/protocol.py", line 154, in fromJson
    return json_format.Parse(json, protoClass())
  File "/usr/local/python/2.7.12-gcc4/externalmodules/lib/python2.7/site-packages/google/protobuf/json_format.py", line 369, in Parse
    return ParseDict(js, message, ignore_unknown_fields)
  File "/usr/local/python/2.7.12-gcc4/externalmodules/lib/python2.7/site-packages/google/protobuf/json_format.py", line 384, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/usr/local/python/2.7.12-gcc4/externalmodules/lib/python2.7/site-packages/google/protobuf/json_format.py", line 415, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/local/python/2.7.12-gcc4/externalmodules/lib/python2.7/site-packages/google/protobuf/json_format.py", line 501, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse variantSets field: Failed to parse metadata field: Message type "ga4gh.schemas.ga4gh.VariantSetMetadata" has no field named "info".`

**Comment by melissacline** [comment]
Zack, would you see that this gets squared away?  Thanks!

**Comment by zfisch** [comment]
@jasteen are you still encountering this issue? If so, could you provide a link to the documentation you're using and exactly what line you're having trouble with?

I'm unable to find `variant_sets = [i for i in c.search_variant_sets(dataset_id="brca")]` as a command in the docs.

**Comment by jasteen** [comment]
https://github.com/BRCAChallenge/brca-exchange/blob/master/website/django/data/static/python_notebook/brca-exchange.ipynb

line 5.  I still get the same error about VariantSetMetadata having now field named info.

**Comment by zfisch** [comment]
@jasteen interesting, i'm not able to recreate this error on osx or ubuntu -- are you using the latest versions?

I'm using the following (all installed using `pip install ga4gh`):

```
ga4gh==0.3.5
ga4gh-client==0.6.0a9
ga4gh-common==0.0.5
ga4gh-schemas==0.6.0a9.post2
```
